#!/bin/python3

import sys

def test_python3_import_imblearn():
    """Tests that imblearn is importable."""
    try:
        import imblearn
    except ImportError as err:
        sys.stderr.write("Could not import imblearn: %s", err)
        sys.exit(1)

if __name__ == "__main__":
    test_python3_import_imblearn()
    sys.exit(0)
