package:
  name: imbalanced-learn
  version: "0.3.1"

source:
  git_rev: 0.3.1
  git_url: https://github.com/scikit-learn-contrib/imbalanced-learn.git

build:
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - scikit-learn 0.19.*

  run:
    - python
    - scikit-learn 0.19.*

test:
  requires:
    - nose
    - coverage
    - pytest
    - pytest-cov
  imports:
    - imblearn

about:
  home: https://github.com/scikit-learn-contrib/imbalanced-learn
  license: MIT
  license_file: LICENSE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
